### ISSUE TITLE
AttributeError: __exit__ with no aliases file

### ISSUE THREAD

**Issue by The-Compiler** [PCManticore/copyrite#1]
With copyrite from git, Python 3.5 and no aliases file:

```
Traceback (most recent call last):
  File "/home/florian/.venv/bin/copyrite", line 9, in <module>
    load_entry_point('copyrite==0.1.0', 'console_scripts', 'copyrite')()
  File "/home/florian/.venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/florian/.venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/florian/.venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/florian/.venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/florian/.venv/lib/python3.5/site-packages/copyrite/cli.py", line 163, in main
    built_aliases = _build_aliases_from_file(aliases)
  File "/home/florian/.venv/lib/python3.5/site-packages/copyrite/cli.py", line 122, in _build_aliases_from_file
    with aliases:
AttributeError: __exit__
```

**Comment by PCManticore** [comment]
Oups, thanks!

**Comment by PCManticore** [comment]
Should be okay now. Sorry, it has no tests for now. ;-)
